OxyPlot.Xamarin.Mac: add reference to netstandard
* fixing errors like this in GHA:
  error CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.